version: '3.8'

services:
  portfolio:
    build: .
    container_name: phill-portfolio
    ports:
      - "90:90"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-default-password-change-me}
    volumes:
      # Mount data directory for persistent visitor tracking
      - ./data:/app/data
    networks:
      - Shared

networks:
  Shared:
    external: true 