version: '3.8'

services:
  portfolio:
    build: .
    container_name: phill-portfolio
    ports:
      - "90:90"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: mount logs for debugging
      - ./logs:/var/log/nginx
    networks:
      - Shared

networks:
  Shared:
    external: true 